Form/Type/DateRangeType.php
<?php

namespace Admingenerator\GeneratorBundle\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class DateRangeType extends AbstractType
{

    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        unset($options['years']);

        $options['from']['required'] = $options['required'];
        $options['to']['required'] = $options['required'];

        if ($options['format']) {
            $options['from']['format'] = $options['format'];
            $options['to']['format'] = $options['format'];
        }
        $options['from']['widget'] = 'single_text';
        $options['to']['widget'] = 'single_text';

        $builder
                ->add('from', new DateType(), $options['from'])
                ->add('to', new DateType(), $options['to']);
    }

    /**
     * {@inheritdoc}
     */
    public function getParent()
    {
        return 'form';
    }

    /**
     * {@inheritdoc}
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {

        $years = range(date('Y'), date('Y') - 120);

        $resolver->setDefaults(
            array(
            'format' => null,
            'years'  => $years,
            'to'     => array('years' => $years, 'widget' => 'choice'),
            'from'   => array('years' => $years, 'widget' => 'choice'),
            'widget' => 'choice')
        );
    }

    /**
     * {@inheritdoc}
     */
    public function getName()
    {
        return 'date_range';
    }
}

Form/Type/DateType.php
<?php

namespace Admingenerator\GeneratorBundle\Form\Type;

use Symfony\Component\Form\FormInterface;
use Symfony\Component\Form\FormView;

class DateType extends \Symfony\Component\Form\Extension\Core\Type\DateType
{

    /**
     * {@inheritdoc}
     */
    public function finishView(FormView $view, FormInterface $form, array $options)
    {
        $view->vars['widget'] = $options['widget'];
        $pattern =  "d MMM y"; //$form->getConfig()->getAttribute('formatter')->getPattern();

        $view->vars['date_pattern'] = $pattern;
        $view->vars['dateFormat'] = $this->convertJqueryDate($pattern);
        $view->vars['locale'] = \Locale::getDefault();
    }

    protected function convertJqueryDate($format)
    {
        //jquery use a different syntax, have to replace
        //  php    jquery
        //  MM      mm
        //  MMM     M
        //  MMMM    MM
        //  y       yy

        if (strpos($format, "MMM") > 0) {
            $format = str_replace("MMM", "M", $format);
        } else {
            $format = str_replace("MM", "mm", $format);
        }
        $format = str_replace("LLL", "M", $format);
        $format = str_replace("y", "yy", $format);

        return $format;
    }

}

src/Nitra/TopsBundle/Form/DataTransformer/ProductionIdToEntityTransformer.php
<?php
namespace Nitra\TopsBundle\Form\DataTransformer;

use Symfony\Component\Form\DataTransformerInterface;
use Symfony\Component\Form\Exception\TransformationFailedException;
use Doctrine\Common\Persistence\ObjectManager;


/**
 * WarehouseIdToEntityTransformer
 */
class ProductionIdToEntityTransformer implements DataTransformerInterface
{
    
    /**
     * @var \Doctrine\ORM\EntityManager
     */
    private $em;
    
    /**
     * Constructor
     * 
     * @param \Doctrine\ORM\EntityManager $em
     */
    public function __construct(\Doctrine\ORM\EntityManager $em)
    {
        
//        var_dump(get_class($em));
////        die('ss');
        

        $this->em = $em;
    }

    /**
     * Transforms an object to a string.
     * @param  object|null $transformObj
     * @return string
     */
    public function transform($transformObj)
    {

        if (null === $transformObj) {
            return "";
        }

        
        return $transformObj->getId();
    }

    /**
     * Transforms a string (id) to an object.
     * @param  string $id
     * @return $transformObj|null
     * @throws TransformationFailedException if object is not found.
     */
    public function reverseTransform($id)
    {

        if (!$id) {
            return null;
        }
        $transformObj = $this->em
            ->getRepository('NitraTopsBundle:Production')
            ->findOneBy(array('id' => $id)) ;

        if (null === $transformObj) {
            throw new TransformationFailedException(sprintf('An object with Id "%s" does not exist!', $id));
        }

        return $transformObj;
    }
}

src/Nitra/TopsBundle/Form/Type/Account/EditType.php
<?php

namespace Nitra\TopsBundle\Form\Type\Account;

use Admingenerated\NitraTopsBundle\Form\BaseAccountType\EditType as BaseEditType;

/**
 * EditType
 */
class EditType extends BaseEditType
{
}

src/Nitra/TopsBundle/Form/Type/Account/FiltersType.php
<?php

namespace Nitra\TopsBundle\Form\Type\Account;

use Admingenerated\NitraTopsBundle\Form\BaseAccountType\FiltersType as BaseFiltersType;

/**
 * FiltersType
 */
class FiltersType extends BaseFiltersType
{
}

src/Nitra/TopsBundle/Form/Type/Account/NewType.php
<?php

namespace Nitra\TopsBundle\Form\Type\Account;

use Admingenerated\NitraTopsBundle\Form\BaseAccountType\NewType as BaseNewType;

/**
 * NewType
 */
class NewType extends BaseNewType
{
}

src/Nitra/TopsBundle/Form/Type/AjaxAutocompleteType.php
<?php

namespace Nitra\TopsBundle\Form\Type;
use Symfony\Component\Form\AbstractType;
//use Admingenerator\GeneratorBundle\Form\Type\AjaxAutocompleteType as AjaxAutocomplete;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\Form\FormView;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

/**
 *
 *
 *       $options = array(
 *           'autocompleteActionRouting' => '',      // Роутинг на контроллер, который будет отдавать данные для списка
 *           'afterItemSelectJavascript' => '',      // Дополнительные Javascript действия после выбора из списка
 *           'extraParamsString' => '',              // Дополнительные Get-параметры отсылаемые в Controller
 *           'minChars' => 2,                        // Минимальная длина запроса для срабатывания автозаполнения
 *           'deferRequestBy' => 10,                 // Задержка запроса (мсек), на случай, если мы не хотим слать миллион запросов, пока пользователь печатает.
 *           'maxHeight' => 400,                     // Максимальная высота списка подсказок, в пикселях
 *           'width' => 300                          // Ширина списка
 *       );
 *
 *
 *
 * Пример контроллера
 * public function testAjaxAction () {
 *
 *       // То что приходит из поля ввода (строка поиска)
 *       $search_str = $this->getRequest()->get('q');
 *
 *       $autocomplete_return = array();
 *
 *       $return_pos['value'] = '2'; // Идентификатор записи, прийдет в посте
 *       $return_pos['label'] = 'label2 Отображается при выборе из списка';  // Название записи, прийдет в посте
 *       $return_pos['display'] = 'label2 отображение во время поиска';
 *       $return_pos['dop_info'] = 'label2dop Дополнительная информация, нигде не отображается';
 *       $return_pos['json_data'] = array(
 *           'id' => '44',
 *           'comment' => 'Test comment2'
 *       );
 *       array_push($autocomplete_return,$return_pos['display'] . "|" . $return_pos['label'] . "|" . $return_pos['value'] . '|' . json_encode($return_pos['json_data']) );
 *
 *
 *       $return_pos['value'] = '3'; // Идентификатор записи, прийдет в посте
 *       $return_pos['label'] = 'label3 Отображается при выборе из списка';  // Название записи, прийдет в посте
 *       $return_pos['display'] = 'label3 отображение во время поиска';
 *       $return_pos['dop_info'] = 'label3dop Дополнительная информация, нигде не отображается';
 *
 *       $return_pos['json_data'] = array(
 *           'id' => '55',
 *           'comment' => 'Test comment3'
 *       );
 *
 *       array_push($autocomplete_return,$return_pos['display'] . "|" . $return_pos['label'] . "|" . $return_pos['value'] . '|' . json_encode($return_pos['json_data']) );
 *
 *       return new Response( implode("\n", $autocomplete_return) );
 *
 *   }
 *
 *
 */
class AjaxAutocompleteType extends AbstractType
{

    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
                ->add('name', 'text')
                ->add('id', 'hidden');
    }

    /**
     * {@inheritdoc}
     */
    public function buildView(FormView $view, FormInterface $form, array $options)
    {

        $view->vars['autocompleteActionRouting'] = $options['autocompleteActionRouting'];
        $view->vars['afterItemSelectJavascript'] = $options['afterItemSelectJavascript'];
        $view->vars['extraParamsString'] = $options['extraParamsString'];
        $view->vars['minChars'] = $options['minChars'];
        $view->vars['deferRequestBy'] = $options['deferRequestBy'];
        $view->vars['maxHeight'] = $options['maxHeight'];
        $view->vars['width'] = $options['width'];

    }
    

    /**
     * {@inheritdoc}
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'autocompleteActionRouting' => '',    // Роутинг на контроллер, который будет отдавать данные для списка
            'afterItemSelectJavascript' => '',   // Дополнительные Javascript действия после выбора из списка
            'extraParamsString' => '',            // Дополнительные Get-параметры отсылаемые в Controller
            'minChars' => 2,                        // Минимальная длина запроса для срабатывания автозаполнения
            'deferRequestBy' => 10,                 // Задержка запроса (мсек), на случай, если мы не хотим слать миллион запросов, пока пользователь печатает.
            'maxHeight' => 400,                     // Максимальная высота списка подсказок, в пикселях
            'width' => 300                          // Ширина списка
        ));
    }

    public function getName()
    {
        return 'ajax_autocomplete';
    }

}

src/Nitra/TopsBundle/Form/Type/Buyer/EditType.php
<?php

namespace Nitra\TopsBundle\Form\Type\Buyer;

use Admingenerated\NitraTopsBundle\Form\BaseBuyerType\EditType as BaseEditType;

/**
 * EditType
 */
class EditType extends BaseEditType
{
}

src/Nitra/TopsBundle/Form/Type/Buyer/FiltersType.php
<?php

namespace Nitra\TopsBundle\Form\Type\Buyer;

use Admingenerated\NitraTopsBundle\Form\BaseBuyerType\FiltersType as BaseFiltersType;

/**
 * FiltersType
 */
class FiltersType extends BaseFiltersType
{
}

src/Nitra/TopsBundle/Form/Type/Buyer/NewType.php
<?php

namespace Nitra\TopsBundle\Form\Type\Buyer;

use Admingenerated\NitraTopsBundle\Form\BaseBuyerType\NewType as BaseNewType;

/**
 * NewType
 */
class NewType extends BaseNewType
{
}

src/Nitra/TopsBundle/Form/Type/CategoryExpense/EditType.php
<?php

namespace Nitra\TopsBundle\Form\Type\CategoryExpense;

use Admingenerated\NitraTopsBundle\Form\BaseCategoryExpenseType\EditType as BaseEditType;

/**
 * EditType
 */
class EditType extends BaseEditType
{
}

src/Nitra/TopsBundle/Form/Type/CategoryExpense/FiltersType.php
<?php

namespace Nitra\TopsBundle\Form\Type\CategoryExpense;

use Admingenerated\NitraTopsBundle\Form\BaseCategoryExpenseType\FiltersType as BaseFiltersType;

/**
 * FiltersType
 */
class FiltersType extends BaseFiltersType
{
}

src/Nitra/TopsBundle/Form/Type/CategoryExpense/NewType.php
<?php

namespace Nitra\TopsBundle\Form\Type\CategoryExpense;

use Admingenerated\NitraTopsBundle\Form\BaseCategoryExpenseType\NewType as BaseNewType;

/**
 * NewType
 */
class NewType extends BaseNewType
{
}

src/Nitra/TopsBundle/Form/Type/Colors/EditType.php
<?php

namespace Nitra\TopsBundle\Form\Type\Colors;

use Admingenerated\NitraTopsBundle\Form\BaseColorsType\EditType as BaseEditType;

/**
 * EditType
 */
class EditType extends BaseEditType
{
}

src/Nitra/TopsBundle/Form/Type/Colors/FiltersType.php
<?php

namespace Nitra\TopsBundle\Form\Type\Colors;

use Admingenerated\NitraTopsBundle\Form\BaseColorsType\FiltersType as BaseFiltersType;

/**
 * FiltersType
 */
class FiltersType extends BaseFiltersType
{
}

src/Nitra/TopsBundle/Form/Type/Colors/NewType.php
<?php

namespace Nitra\TopsBundle\Form\Type\Colors;

use Admingenerated\NitraTopsBundle\Form\BaseColorsType\NewType as BaseNewType;

/**
 * NewType
 */
class NewType extends BaseNewType
{
}

src/Nitra/TopsBundle/Form/Type/Expense/EditType.php
<?php

namespace Nitra\TopsBundle\Form\Type\Expense;

use Admingenerated\NitraTopsBundle\Form\BaseExpenseType\EditType as BaseEditType;

/**
 * EditType
 */
class EditType extends BaseEditType
{
}

src/Nitra/TopsBundle/Form/Type/Expense/FiltersType.php
<?php

namespace Nitra\TopsBundle\Form\Type\Expense;

use Admingenerated\NitraTopsBundle\Form\BaseExpenseType\FiltersType as BaseFiltersType;

/**
 * FiltersType
 */
class FiltersType extends BaseFiltersType
{
}

src/Nitra/TopsBundle/Form/Type/Expense/NewType.php
<?php

namespace Nitra\TopsBundle\Form\Type\Expense;

use Admingenerated\NitraTopsBundle\Form\BaseExpenseType\NewType as BaseNewType;

/**
 * NewType
 */
class NewType extends BaseNewType
{
}

src/Nitra/TopsBundle/Form/Type/Income/EditType.php
<?php

namespace Nitra\TopsBundle\Form\Type\Income;

use Admingenerated\NitraTopsBundle\Form\BaseIncomeType\EditType as BaseEditType;

/**
 * EditType
 */
class EditType extends BaseEditType
{
}

Resources/views/Form/fields.html.twig
{% block form_widget_compound %}
{% spaceless %}
    <div {{ block('widget_container_attributes') }}>
        {% if form.parent is empty %}
            {{ form_errors(form) }}
        {% endif %}
        {{ block('form_rows') }}
        {{ form_rest(form) }}
    </div>
{% endspaceless %}
{% endblock form_widget_compound %}

{% block form_rows %}
{% spaceless %}
    {% if options is defined %}
        {% for child in form %}
            {{ form_row(child, options) }}
        {% endfor %}
    {% else %}
        {% for child in form %}
            {{ form_row(child) }}
        {% endfor %}
    {% endif %}
{% endspaceless %}
{% endblock form_rows %}

{% block form_row %}
{% spaceless %}
    <div class="form_row field_{{ form.vars.name }} {% if errors|length > 0 %} field_error{% endif %}">
        {{ form_label(form) }}
        <div class="field_content">
            {{ form_errors(form) }}
            {{ form_widget(form) }}
            {{ block('form_help') }}
        </div>
    </div>
{% endspaceless %}
{% endblock form_row %}

{% block form_label %}
{% spaceless %}
    {% if not compound %}
        {% set label_attr = label_attr|merge({'for': id}) %}
    {% endif %}
    {% if required %}
        {% set label_attr = label_attr|merge({'class': (label_attr.class|default('') ~ ' required')|trim}) %}
    {% endif %}
    {% if label is empty %}
        {% set label = name|humanize %}
    {% endif %}
    <label{% for attrname, attrvalue in label_attr %} {{ attrname }}="{{ attrvalue }}"{% endfor %}>{{ label|trans({}, translation_domain) }}</label>
{% endspaceless %}
{% endblock form_label %}

{% block form_errors %}
{% spaceless %}
    {% if errors|length > 0 %}
    <ul class="errors">
        {% for error in errors %}
            <li>{{
                error.messagePluralization is null
                    ? error.messageTemplate|trans(error.messageParameters, 'validators')
                    : error.messageTemplate|transchoice(error.messagePluralization, error.messageParameters, 'validators')
            }}</li>
        {% endfor %}
    </ul>
    {% endif %}
{% endspaceless %}
{% endblock form_errors %}

{# --- FORM ROWS --- #}

{% block date_range_row %}
    {% spaceless %}
        <div class="form_row field_date_range">
            {{ form_label(form) }}
            <div class="field_content">
                {{ form_errors(form) }}
                {{ form_widget(form) }}
            </div>
        </div>
    {% endspaceless %}
{% endblock date_range_row %}



{# --- FORM WIDGETS --- #}

{% block date_widget %}
    {% spaceless %}
        {{ block('form_widget_simple') }}
        <script>
            $(function() {
              $( "#{{ id }}" ).datepicker({
                  dateFormat: '{{ dateFormat }}',
                });
              $.datepicker.setDefaults($.datepicker.regional['{{locale}}']);
            });
        </script>
    {% endspaceless %}
{% endblock date_widget %}
        
{% block choice_widget_expanded %}
{% spaceless %}
        <ul {{ block('widget_container_attributes') }} class="collection">
            {% for child in form %}
                <li>
                    {{ form_widget(child) }}
                    {{ form_label(child) }}
                </li>        
            {% endfor %}
        </ul>        
{% endspaceless %}
{% endblock choice_widget_expanded %}        

{% block double_list_widget %}
{% spaceless %}
    <script type="text/javascript" src="{{ asset('bundles/admingeneratorgenerator/javascripts/double_list.js') }}"></script>
    <div class="double_list">
        <div class="double_list_unselected">
            {% include "AdmingeneratorGeneratorBundle:Form/DoubleList:unselected_list.html.twig" %}
        </div>
        <div class="double_list_links">
            <a href="#" class="next" onclick="sfDoubleList.move('{{ id }}_unselected','{{ id }}_selected'); return false;"></a>
            <br />
            <a href="#" class="prev" onclick="sfDoubleList.move('{{ id }}_selected','{{ id }}_unselected'); return false;"></a>
        </div>
        <div class="double_list_selected">
            {% include "AdmingeneratorGeneratorBundle:Form/DoubleList:selected_list.html.twig" %}
        </div>
        {% include "AdmingeneratorGeneratorBundle:Form/DoubleList:javascript.html.twig" %}
    </div>
{% endspaceless %}
{% endblock %}


{% block ajax_autocomplete_widget %}

    {% spaceless %}
        {{ form_widget(form.name) }}
        {{ form_widget(form.id) }}
    {% endspaceless %}

    {% stylesheets '@AdmingeneratorGeneratorBundle/Resources/public/css/jquery.autocomplete.css' %}
            <link rel="stylesheet" href="{{ asset_url }}" />
    {% endstylesheets %}

    {% javascripts '@AdmingeneratorGeneratorBundle/Resources/public/js/jquery.autocomplete.js' %}
            <script src="{{ asset_url }}"></script>
    {% endjavascripts %}
            
{% block ajax_autocomplete_js %}
    {% spaceless %}

        <script type="text/javascript">

          (function(){
                $('#{{ form.name.vars.id }}').autocomplete('{{ path (autocompleteActionRouting) }}', {
                    minChars: {{ minChars }},
                    delimiter: /(,|;)\s*/,
                    maxHeight: {{ maxHeight }},
                    width: {{ width }},
                    zIndex: 9999,
                    deferRequestBy: {{ deferRequestBy }},
                    dataType: "json",
                    extraParams: {
                        {{ extraParamsString | raw }}
                    },

                    onItemSelect: function(row) {


                            {# Для использования json данных необходимо в Контроллере,
                               который возвращает данные для выпадающего списка возвращать данные в следующем формате

$Строка_отображения_во_время_набора_с_клавиатуры . "|" . $Строка_которая_подставиться_при_выборе_из_списка . "|" . $Идентификатор . '|' . json_encode($json-данные_для_обработки_в_скрипте)

                            Сюда данные прийдут в переменной row.extra[2]
                            Для превращения их в Javascript-массив выполняем следующее

                            value1 = eval('('+row.extra[2]+')');

                            После чего в value1 у нас javascript-массив, к елементам которго можно обращатся value1.ключ_в_массиве

                            #}

                            $('#{{ form.name.vars.id }}').val(row.extra[0]);
                            $('#{{ form.id.vars.id }}').val(row.extra[1]);

                            {{ afterItemSelectJavascript | raw }}
                        }

                }).change(function(){
                                        if (!$.trim(this.value)) {
                                            $('#{{ form.id.vars.id }}').val('').change();
                                        }

                                    });
       })();
        </script>
    {% endspaceless %}
{% endblock ajax_autocomplete_js %}        
{% endblock ajax_autocomplete_widget %}